fos_user_profile_show:
    path: /
    methods: [GET]
    defaults: { _controller: FOSUserBundle:Profile:show }
fos_user_profile_edit:
    path: /editer
    methods: [GET, POST]
    defaults: { _controller: FOSUserBundle:Profile:edit }