fos_user_registration_register:
    path: /
    methods: [GET, POST]
    defaults: { _controller: FOSUserBundle:Registration:register}
fos_user_registration_check_email:
    path: /verificationemail
    methods: [GET]
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }
fos_user_registration_confirm:
    path: /confirme/{token}
    methods: [GET]
    defaults: { _controller: FOSUserBundle:Registration:confirm }
fos_user_registration_confirmed:
    path: /confirmer
    methods: [GET]
    defaults: { _controller: FOSUserBundle:Registration:confirmed }