fos_user_security_login:
    path: /connexion
    methods: [GET, POST]
    defaults: { _controller: FOSUserBundle:Security:login }
fos_user_security_check:
    path: /verification
    methods: [POST]
    defaults: { _controller: FOSUserBundle:Security:check }
fos_user_security_logout:
    path: /deconnexion
    methods: [GET, POST]
    defaults: { _controller: FOSUserBundle:Security:logout }