<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findObservationsBySpecieId($id){

        $observations = $this->createQueryBuilder('o')
            ->where('o.specy = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $observations;
    }

    public function findObservationById($id){
        var_dump($id);
        $observation = $this->createQueryBuilder('o')
            ->where('o.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();

            return $observation;
    }
}
