<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findObservationsBySpecieId($id){
        $observations = $this->createQueryBuilder('o')
            ->where('o.specy = :id')
            ->setParameter('id', $id)
            ->orderBy('o.id', 'DESC')
            ->getQuery()
            ->getResult();

        return $observations;
    }

    public function findObservationById($id){
        $observation = $this->createQueryBuilder('o')
            ->where('o.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();

            return $observation;
    }

    public function getNumberOfObservationsByBird($birdCdNom){
        $number = $this->createQueryBuilder('n')
            ->select('COUNT(n.specy)')
            ->where('n.specy = :specy')
            ->setParameter('specy', $birdCdNom)
            ->getQuery()
            ->getSingleScalarResult();
        return $number;
    }


    public function findLastObservations($limit){
        $list = $this->createQueryBuilder('l')
            ->orderBy('l.id', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

        return $list;
    }
}
