<?php

namespace AppBundle\Repository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findObservationsBySpecieId($id){
        $id = 1;
        $specy = $this->createQueryBuilder('o')
            ->where('o.specie = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $specy;
    }
}
