services:
    app.observation_creation:
            class: AppBundle\Service\observationCreation
            arguments: [ "@doctrine.orm.entity_manager" ]
    app.envoi_email:
            class: AppBundle\Service\SendEmail
            arguments: [ "@mailer", "@templating", "@service_container", "@request_stack" ]
    app.random_landing:
                class: AppBundle\Service\randomLanding
    app.convert_array:
                class: AppBundle\Service\ConvertCsvToArray
    app.delete_image:
                    class: AppBundle\Service\DeleteImage
    app.flashbag_fosuser:
                class: AppBundle\Service\FlashBagFosUser
                arguments: [ "@session" ]
    app.check_size_image:
                class: AppBundle\Validator\CheckImageSizeValidator
                arguments: [ "@session" ]
                tags:
                        - { name: validator.constraint_validator, alias: app_check_size_image }
    app.check_type_image:
                    class: AppBundle\Validator\CheckImageTypeValidator
                    arguments: [ "@session" ]
                    tags:
                            - { name: validator.constraint_validator, alias: app_check_type_image }
