AppBundle\Entity\Taxref:
    type: entity
    table: taxref
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        regne:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: REGNE
        phylum:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: PHYLUM
        classe:
            type: string
            nullable: true
            length: 4
            options:
                fixed: false
            column: CLASSE
        ordre:
            type: string
            nullable: true
            length: 19
            options:
                fixed: false
            column: ORDRE
        famille:
            type: string
            nullable: true
            length: 17
            options:
                fixed: false
            column: FAMILLE
        cdNom:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_NOM
        cdTaxsup:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_TAXSUP
        cdRef:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_REF
        rang:
            type: string
            nullable: true
            length: 4
            options:
                fixed: false
            column: RANG
        lbNom:
            type: string
            nullable: true
            length: 47
            options:
                fixed: false
            column: LB_NOM
        lbAuteur:
            type: string
            nullable: true
            length: 51
            options:
                fixed: false
            column: LB_AUTEUR
        nomComplet:
            type: string
            nullable: true
            length: 83
            options:
                fixed: false
            column: NOM_COMPLET
        nomValide:
            type: string
            nullable: true
            length: 83
            options:
                fixed: false
            column: NOM_VALIDE
        nomVern:
            type: string
            nullable: true
            length: 101
            options:
                fixed: false
            column: NOM_VERN
        nomVernEng:
            type: string
            nullable: true
            length: 122
            options:
                fixed: false
            column: NOM_VERN_ENG
        habitat:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: HABITAT
        fr:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: FR
        gf:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: GF
        mar:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: MAR
        gua:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: GUA
        sm:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: SM
        sb:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: SB
        spm:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: SPM
        may:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: MAY
        epa:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: EPA
        reu:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: REU
        sa:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: SA
        ta:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: TA
        taaf:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: TAAF
        nc:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: NC
        wf:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: WF
        pf:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: PF
        cli:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: CLI
    lifecycleCallbacks: {  }
